import type { OwnerKind } from "./manifest.ts";

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function layout(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<style>
:root{color-scheme:light dark}
body{font:16px/1.6 system-ui,sans-serif;max-width:42rem;margin:3rem auto;padding:0 1rem}
code,pre{font-family:ui-monospace,monospace;background:rgba(127,127,127,.15);border-radius:4px}
code{padding:.1em .3em}
pre{padding:.8rem 1rem;overflow:auto}
label{display:block;margin:.8rem 0 .2rem}
input,select,button{font:inherit;padding:.4rem .6rem}
button{margin-top:1rem;cursor:pointer}
</style>
</head>
<body>
${body}
</body>
</html>`;
}

export function html(body: string, status = 200): Response {
  return new Response(body, {
    status,
    headers: { "content-type": "text/html; charset=utf-8" },
  });
}

export function setupWizardPage(): string {
  return layout(
    "Set up the runner",
    `<h1>Set up the runner</h1>
<p>This creates a private GitHub App for this deployment. The App credentials are generated by GitHub and stored only in this Worker. After setup this page becomes read-only.</p>
<form method="post" action="/setup/start">
<label for="kind">App owner</label>
<select id="kind" name="kind">
<option value="org">Organization</option>
<option value="user">Personal account</option>
</select>
<label for="org">Organization name (organization only)</label>
<input id="org" name="org" placeholder="example-org" autocomplete="off">
<button type="submit">Create the GitHub App</button>
</form>
<p>The owner must be listed in <code>ALLOWED_OWNERS</code> for this deployment, otherwise the App is rejected.</p>`,
  );
}

export function manifestRedirectPage(
  action: string,
  manifestJson: string,
): string {
  return layout(
    "Redirecting to GitHub",
    `<p>Redirecting to GitHub&hellip;</p>
<form id="f" method="post" action="${escapeHtml(action)}">
<input type="hidden" name="manifest" value="${escapeHtml(manifestJson)}">
<noscript><button type="submit">Continue to GitHub</button></noscript>
</form>
<script>document.getElementById("f").submit()</script>`,
  );
}

export function installUrl(slug: string): string {
  return `https://github.com/apps/${encodeURIComponent(slug)}/installations/new`;
}

export function configuredPage(slug: string, labelPrefix: string): string {
  return layout(
    "Runner is configured",
    `<h1>Runner is configured</h1>
<p>GitHub App: <code>${escapeHtml(slug)}</code></p>
<p><a href="${escapeHtml(installUrl(slug))}">Install the App on repositories</a></p>
<h2>Usage</h2>
<pre>runs-on:
  - ${escapeHtml(labelPrefix)}-\${{ github.run_id }}-\${{ github.run_attempt }}
  - instance:standard-2</pre>
<p>Setup cannot be changed from this page.</p>`,
  );
}

export function messagePage(
  title: string,
  message: string,
  status: number,
): Response {
  return html(
    layout(title, `<h1>${escapeHtml(title)}</h1><p>${escapeHtml(message)}</p>`),
    status,
  );
}

export function parseOwnerKind(value: string | null): OwnerKind {
  return value === "user" ? "user" : "org";
}
